/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import juegoprogra.Batalla;
import juegoprogra.Luchador;
import juegoprogra.Monstruo;
import juegoprogra.ObjetoEquipable;
/**
 *
 * @author diegosaurio
 */
public class MenuBattalla extends javax.swing.JFrame {
private ArrayList<Luchador> listaLuchadores = null;
 private ArrayList<ObjetoEquipable> listaObjetos = null;
    /**
     * Creates new form MenuBattalla
     */
    public MenuBattalla(ArrayList<Luchador> paramListaLuchadores,ArrayList<ObjetoEquipable> listaObjetos) {
        initComponents();
        this.setLocationRelativeTo(null);
        listaLuchadores = paramListaLuchadores;
        tablaLuchadores2.setModel(agregarLuchadorTabla(listaLuchadores));
    }
 public DefaultTableModel agregarLuchadorTabla(ArrayList<Luchador> listaLuchadores) {
        
        try {
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("Numero");
            dtm.addColumn("Nombre");
            dtm.addColumn("Atk");
            dtm.addColumn("Def ");
            dtm.addColumn("Spd");
            dtm.addColumn("Hp");
            dtm.addColumn("Faccion");
            dtm.addColumn("Rango");
            dtm.addColumn("Objeto");
            Object arreglo[] = new Object[9];
            int numero = 1;
            for (int contador = 0; contador < listaLuchadores.size(); contador++) {
                arreglo[0] = String.valueOf(numero);
                arreglo[1] = listaLuchadores.get(contador).getNombre();
                arreglo[2] = String.valueOf(listaLuchadores.get(contador).getAtk());
                arreglo[3] = String.valueOf(listaLuchadores.get(contador).getDef());
                arreglo[4] = String.valueOf(listaLuchadores.get(contador).getSpd());
                arreglo[5] = String.valueOf(listaLuchadores.get(contador).getHp());
                arreglo[6] = listaLuchadores.get(contador).getFaccion();
                arreglo[7] = String.valueOf(listaLuchadores.get(contador).getRango());
                arreglo[8] = String.valueOf(listaLuchadores.get(contador).getIsObjetoEquipado());
                dtm.addRow(arreglo);
                numero++;
            }
            return dtm;
        } catch (Exception e) {
            System.out.println(e);
            return null;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaLuchadores2 = new javax.swing.JTable();
        bPelear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaLuchadores2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Atk", "Def", "Spd", "Hp", "Faccion", "Rango", "Objeto"
            }
        ));
        jScrollPane2.setViewportView(tablaLuchadores2);

        bPelear.setText("Pelear!");
        bPelear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPelearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bPelear, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(bPelear, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPelearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPelearActionPerformed
        Batalla batalla= new Batalla();
        Monstruo monstruo = new Monstruo();
        listaLuchadores=batalla.pelear(listaLuchadores, monstruo,listaObjetos);
        String mensaje=batalla.getDesarrolloBatalla();
        JTextArea textArea = new JTextArea(mensaje);
        textArea.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(textArea);  
        textArea.setLineWrap(true);  
        textArea.setWrapStyleWord(true); 
        scrollPane.setPreferredSize( new Dimension( 500, 500 ) );
        JOptionPane.showMessageDialog(null, scrollPane, "dialog test with textarea", JOptionPane.YES_NO_OPTION);
        MenuPrincipal menu = new MenuPrincipal(listaLuchadores,listaObjetos);
        menu.setVisible(true);
        this.setVisible(false);
        //JOptionPane.showMessageDialog(null,mensaje);
        
        /*JTextArea texto = new JTextArea(10, 10);
        texto.setEditable(false);
        texto.setText(mensaje);
        panel1= new JScrollPane(texto);
        panel1.revalidate();
        panel1.repaint();
        */
    }//GEN-LAST:event_bPelearActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPelear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaLuchadores2;
    // End of variables declaration//GEN-END:variables
}
